#!/usr/bin/env bash
# 4th adn 8th loop are replaced

i=0;
while ((i <= 9))
do
	if ((i == 4))
	then
		echo "bad luck"
	elif ((i == 8))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
((i++));
done
