#!/usr/bin/env bash
# 4 9 and 17 are bad

i=0;
while ((i <= 19))
do
	echo $"$i"
	case "$i" in
		3) echo 'bad luck from China'
			;;
		8) echo 'bad luck from Japan'
			;;
		16) echo 'bad luck from Italy'
	esac
((i++));
done
