#!/usr/bin/env bash
# 4 9 and 17 are bad

i=0;
while ((i <= 19))
do
	if ((i == 3))
	then
		echo "bad luck from China"
	elif ((i == 8))
	then
		echo "bad luck from Japan"
	elif ((i == 16))
	then
		echo "bad luck from Italy"
	else
		echo "Best School"
	fi
((i++));
done
