#!/usr/bin/env bash
# information on the school file

FILE=school
if [ -e "$FILE" ]
then
	echo "school file exists"
		if [ -s "$FILE" ]
		then
			echo "school file is not empty"
			if [ -f "$FILE" ]
			then
				echo "school file is a regular file"
			fi
		else
			echo "school file is empty"
		fi
else
	echo "school file does not exist"
fi
